### ISSUE TITLE
User count and ping

### ISSUE THREAD

**Issue by pramadhana92** [azlux/pymumble#114] opened 2021-07-26 16:06 UTC
Hi,

Can we get user count and ping result using pymumble like we get in mumble client in desktop?

![image](https://user-images.githubusercontent.com/44948853/127021704-bf00c795-7e26-4cfa-b449-608ac453dbf4.png)

Thanks!

**Comment by azlux** [comment] 2021-07-26 16:50
Duplicate of https://github.com/azlux/pymumble/issues/103
Please check this issue.

**Closed as completed by azlux** 2021-07-26 16:50 UTC

**Comment by pramadhana92** [comment] 2021-07-26 16:56
thanks a lot for your answer!
