### ISSUE TITLE
multiple instances of pymumble on raspberry pi zero

### ISSUE THREAD

**Issue by spriggsy** [azlux/pymumble#91] opened 2021-01-03 18:49 UTC
Im trying to have pymumble run twice on the same hardware, this is so that it can monitor and speak in multiple rooms at once.

it all works fine apart from the sound received handler. as soon as it detects any sound it crashes. has anyone tried this in the past?

**Comment by azlux** [comment] 2021-01-07 13:34
Hi,
Do you have the crash log  please ?

**Comment by azlux** [comment] 2021-04-17 23:34
Can you give me more information ? I will close this issue if not. I'm not able to reproduce the issue on my raspberry B+.

**Closed as completed** 2021-05-07 21:58 UTC
